image:
  file: .cde.Dockerfile

tasks:
  - name: Cosmosdb
    init: |
      docker pull mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    command: |
      docker run \
        --publish 8081:8081 \
        --publish 10250-10255:10250-10255 \
        --tty \
        mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
        gp sync-done cosmosrun
  - name: CosmosCert
    command: |
      gp sync-await cosmosrun
      curl -k https://localhost:8081/_explorer/emulator.pem > ~/emulatorcert.crt
      sudo cp ~/emulatorcert.crt /usr/local/share/ca-certificates/
      sudo update-ca-certificates

vscode:
  extensions:
    - hashicorp.terraform
    - ms-azuretools.vscode-azureresourcegroups
    - formulahendry.code-runner
    - gitpod.gitpod-desktop
    - ms-dotnettools.csdevkit
    - patcx.vscode-nuget-gallery
