networks:
  default:
    external: false
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

services:
  cosmosdb:
    restart: always
    container_name: "azure-cosmos-emulator-latest"
    hostname: "azurecosmosemulator"
    image: 'mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest'
    mem_limit: 4GB
    tty: true
    ports:
    - '8081:8081' # Data Explorer
    - '8900:8900'
    - '8901:8901'
    - '8902:8902'
    - '10250:10250'
    - '10251:10251'
    - '10252:10252'
    - '10253:10253'
    - '10254:10254'
    - '10255:10255'
    - '10256:10256'
    - '10350:10350'
    expose:
    - "8081"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=11
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=172.16.238.246
    volumes:
      - cosmosdb-dog_adopter_console-data:/var/lib/cosmosdb
    networks:
      default:
        ipv4_address: 172.16.238.246

  app:
    container_name: dog_adopter_console
    build:
      context: .
      dockerfile: .Dockerfile
      args:
      - environment=Development
    depends_on:
      - cosmosdb
    environment:
      - COSMOS_CONN=AccountEndpoint=https://azurecosmosemulator:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==; 
    networks:
      default:
        ipv4_address: 172.16.238.242

volumes:
  cosmosdb-dog_adopter_console-data: